import { CategorySeed } from '../../../interfaces';

// Sources: Gumroad's open-source taxonomy (antiwork/gumroad) and Selar's product guides, adapted for African creators.
// Names here derive each category's seedKey: renaming an entry in this file seeds it as a new category.
export const productCategories: CategorySeed[] = [
  {
    name: 'Business & Money',
    description: 'Starting, growing and running a business, and managing money',
    subcategories: [
      'Entrepreneurship',
      'Digital Marketing',
      'Social Media Growth',
      'Sales',
      'E-commerce & Dropshipping',
      'Freelancing',
      'Personal Finance',
      'Investing & Trading',
      'Forex & Crypto',
      'Real Estate',
      'Accounting & Bookkeeping',
      'Career & Job Search',
      'Leadership & Management',
    ],
  },
  {
    name: 'Education & Exam Prep',
    description: 'Learning resources, study materials and exam preparation',
    subcategories: [
      'JAMB & UTME',
      'WAEC & NECO',
      'University & Postgraduate',
      'Professional Certifications',
      'Language Learning',
      'Mathematics',
      'Science',
      'Social Studies',
      'Study Guides & Notes',
      'Kids & Early Learning',
    ],
  },
  {
    name: 'Software & Technology',
    description: 'Code, apps, tools and tech skills',
    subcategories: [
      'Programming',
      'Web Development',
      'App Development',
      'Data & AI',
      'Cybersecurity',
      'Software & Plugins',
      'No-Code Tools',
      'IT & Networking',
      'Hardware',
    ],
  },
  {
    name: 'Design',
    description: 'Design assets, kits and design skills',
    subcategories: [
      'Graphic Design',
      'UI & Web Design',
      'Branding & Logos',
      'Icons',
      'Fonts',
      'Mockups',
      'Print & Packaging',
      'Social Media Templates',
      'Presentation Templates',
    ],
  },
  {
    name: 'Templates & Productivity',
    description: 'Ready-to-use templates, planners and tools',
    subcategories: [
      'Notion Templates',
      'Spreadsheets & Excel',
      'Canva Templates',
      'Planners & Journals',
      'Resume & CV Templates',
      'Business Documents & Contracts',
      'Printables',
    ],
  },
  {
    name: 'Books & Ebooks',
    description: 'Fiction, non-fiction and other published works',
    subcategories: [
      'Fiction',
      'Non-fiction',
      'Poetry',
      'Biographies & Memoirs',
      "Children's Books",
      'Comics & Graphic Novels',
      'Audiobooks',
    ],
  },
  {
    name: 'Writing & Publishing',
    description: 'Writing skills, publishing and content creation',
    subcategories: [
      'Copywriting',
      'Content Writing & Blogging',
      'Self-Publishing',
      'Scriptwriting & Screenplays',
      'Ghostwriting',
    ],
  },
  {
    name: 'Music & Audio',
    description: 'Music, beats, sound and audio content',
    subcategories: [
      'Beats & Instrumentals',
      'Recorded Music',
      'Sample Packs & Sound Effects',
      'Music Production',
      'Instrument Lessons',
      'Singing & Vocals',
      'Podcasts',
    ],
  },
  {
    name: 'Film & Video',
    description: 'Films, skits and video production',
    subcategories: [
      'Movies & Short Films',
      'Comedy & Skits',
      'Video Production & Editing',
      'Video Templates & LUTs',
      'Filmmaking',
      'Animation',
    ],
  },
  {
    name: 'Photography',
    description: 'Photography assets and skills',
    subcategories: [
      'Lightroom Presets',
      'Photoshop Actions & Overlays',
      'Stock Photos',
      'Photography Lessons',
      'Phone Photography',
    ],
  },
  {
    name: 'Drawing & Art',
    description: 'Illustration, painting and art resources',
    subcategories: [
      'Digital Illustration',
      'Painting',
      'Procreate Brushes',
      'Art Prints',
      'Colouring Pages',
    ],
  },
  {
    name: '3D & AR/VR',
    description: '3D models, assets and immersive content',
    subcategories: [
      '3D Models & Assets',
      'Textures & Materials',
      'Avatars',
      'AR/VR',
    ],
  },
  {
    name: 'Gaming',
    description: 'Games, game assets and gaming guides',
    subcategories: [
      'Game Assets',
      'Game Guides & Coaching',
      'Mods',
      'Tabletop & RPG',
    ],
  },
  {
    name: 'Health & Fitness',
    description: 'Exercise, nutrition and wellbeing',
    subcategories: [
      'Workout Programs',
      'Nutrition & Meal Plans',
      'Weight Management',
      'Yoga & Meditation',
      'Mental Health',
      'Medical & Nursing',
    ],
  },
  {
    name: 'Self Improvement',
    description: 'Personal growth and life skills',
    subcategories: [
      'Personal Development',
      'Productivity & Habits',
      'Public Speaking',
      'Relationships & Dating',
      'Marriage & Family',
      'Parenting',
    ],
  },
  {
    name: 'Faith & Spirituality',
    description: 'Devotionals, sermons and spiritual growth',
    subcategories: [
      'Christianity',
      'Islam',
      'Devotionals',
      'Sermons & Teachings',
      'Spirituality & Mindfulness',
    ],
  },
  {
    name: 'Food & Cooking',
    description: 'Recipes, cooking and food business',
    subcategories: [
      'Recipes & Cookbooks',
      'African Cuisine',
      'Baking & Pastry',
      'Drinks & Smoothies',
      'Catering & Food Business',
    ],
  },
  {
    name: 'Fashion & Beauty',
    description: 'Fashion design, style and beauty',
    subcategories: [
      'Fashion Design',
      'Sewing Patterns',
      'Makeup',
      'Hair Care & Styling',
      'Skincare',
      'Modelling',
    ],
  },
  {
    name: 'Crafts & DIY',
    description: 'Handmade crafts and do-it-yourself projects',
    subcategories: [
      'Knitting & Crochet',
      'Jewellery & Bead Making',
      'Home Decor',
      'Event Decoration',
      'Soap, Candles & Cosmetics Making',
      'Woodworking',
    ],
  },
  {
    name: 'Agriculture',
    description: 'Farming and agribusiness',
    subcategories: [
      'Crop Farming',
      'Poultry',
      'Fish Farming',
      'Livestock',
      'Agribusiness',
    ],
  },
  {
    name: 'Travel & Lifestyle',
    description: 'Travel guides and lifestyle content',
    subcategories: [
      'Travel Guides',
      'Study & Work Abroad',
      'Home & Living',
      'Outdoors',
    ],
  },
  {
    name: 'Other',
    description: 'Products that do not fit another category',
    subcategories: [],
  },
];
