const AG = 'Agric Commodities';
const SM = 'Solid Minerals';

export const isNewCodeDeterminant = 'Bird Eye Chili Peppers';

export const productTypes = [
  {
    name: 'Birds Eye Chilli,Soya Beans,Ginger,Cloves,Hibiscus,Cocoa,Sesame Seeds,Cashew Nut,Mineral',
    field: 'Organoleptic Description',
    valueType: 'string',
    fieldType: 'textarea',
    fieldOptions: [],
    category: `${AG},${AG},${AG},${AG},${AG},${AG},${AG},${AG},${SM}`,
    newName:
      'Bird Eye Chili Peppers,Soy Beans,Ginger,Cassava Cloves,Hibiscus,Cocoa,Sesame Seeds,Cashew Nut,Coal.Gold.Iron Ore.Lead.Lime Stone.Marble.Tin',
  },
  {
    name: 'Cashew Nut',
    field: 'Out Turn',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: AG,
    newName: 'Cashew Nut',
  },
  {
    name: 'Cashew Nut,Birds Eye Chilli,Soya Beans,Ginger,Cloves,Hibiscus,Mineral,Cocoa,Hibiscus',
    field: 'Moisture',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${AG},${AG},${AG},${AG},${AG},${SM},${AG},${AG}`,
    newName:
      'Cashew Nut,Bird Eye Chili Peppers,Soy Beans,Ginger,Cassava Cloves,Hibiscus,Coal.Gold.Iron Ore.Lead.Lime Stone.Marble.Tin,Cocoa,Hibiscus',
  },
  {
    name: 'Cashew Nut,Mineral,Cocoa',
    field: 'Colour',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${SM},${AG}`,
    newName: 'Cashew Nut,Coal.Gold.Iron Ore.Lead.Lime Stone.Marble.Tin,Cocoa',
  },
  {
    name: 'Cashew Nut,Mineral,Cocoa',
    field: 'Defective',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${SM},${AG}`,
    newName: 'Cashew Nut,Coal.Gold.Iron Ore.Lead.Lime Stone.Marble.Tin,Cocoa',
  },
  {
    name: 'Cashew Nut,Cocoa',
    field: 'Nut Count',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${AG}`,
    newName: 'Cashew Nut,Cocoa',
  },
  {
    name: 'Cashew Nut,Mineral,Cocoa',
    field: 'Max Foreign Matter',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${SM},${AG}`,
    newName: 'Cashew Nut,Coal.Gold.Iron Ore.Lead.Lime Stone.Marble.Tin,Cocoa',
  },
  {
    name: 'Birds Eye Chilli,Ginger,Cloves,Mineral,Cocoa',
    field: 'Origin',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${AG},${AG},${AG},${AG}`,
    newName:
      'Bird Eye Chili Peppers,Ginger,Cassava Cloves,Coal.Gold.Iron Ore.Lead.Lime Stone.Marble.Tin,Cocoa',
  },
  {
    name: 'Birds Eye Chilli',
    field: 'SHU (ASTA Method)',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: AG,
    newName: 'Bird Eye Chili Peppers',
  },
  {
    name: 'Birds Eye Chilli,Mineral',
    field: 'Cleaning',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${SM}`,
    newName:
      'Bird Eye Chili Peppers,Coal.Gold.Iron Ore.Lead.Lime Stone.Marble.Tin',
  },
  {
    name: 'Cocoa,Birds Eye Chilli,Soya Beans,Hibiscus',
    field: 'Foreign Matter',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${AG},${AG},${AG}`,
    newName: 'Cocoa,Bird Eye Chili Peppers,Soy Beans,Hibiscus',
  },
  {
    name: 'Birds Eye Chilli,Cocoa',
    field: 'Damaged and Discoloured Pods',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${AG}`,
    newName: 'Bird Eye Chili Peppers,Cocoa',
  },
  {
    name: 'Birds Eye Chilli',
    field: 'Loose Seeds',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Bird Eye Chili Peppers',
  },
  {
    name: 'Birds Eye Chilli,Cocoa',
    field: 'Year of Crop',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${AG}`,
    newName: 'Bird Eye Chili Peppers,Cocoa',
  },
  {
    name: 'Sesame Seeds,Soya Beans,Ginger',
    field: 'Oil Content',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${AG},${AG}`,
    newName: 'Sesame Seeds,Soy Beans,Ginger',
  },
  {
    name: 'Soya Beans',
    field: 'Green Beans',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Soy Beans',
  },
  {
    name: 'Soya Beans',
    field: 'Immature or Shrivelled Beans %',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Soy Beans',
  },
  {
    name: 'Soya Beans',
    field: 'Protein',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Soy Beans',
  },
  {
    name: 'Soya Beans,Cocoa',
    field: 'Beans Count',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${AG}`,
    newName: 'Soy Beans,Cocoa',
  },
  {
    name: 'Mineral,Sesame Seeds',
    field: 'Impurities',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${SM},${AG}`,
    newName: 'Coal.Gold.Iron Ore.Lead.Lime Stone.Marble.Tin,Sesame Seeds',
  },
  {
    name: 'Ginger,Hibiscus',
    field: 'Total Ash',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${AG}`,
    newName: '',
  },
  {
    name: 'Ginger',
    field: 'Acid Insoluble Ash',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: '',
  },
  {
    name: 'Cloves',
    field: 'Stems',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Cassava Cloves',
  },
  {
    name: 'Cloves,Mineral',
    field: 'Odd Matters',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${SM}`,
    newName: 'Cassava Cloves,Coal.Gold.Iron Ore.Lead.Lime Stone.Marble.Tin',
  },
  {
    name: 'Cloves',
    field: 'Smell',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Cassava Cloves',
  },
  {
    name: 'Cloves,Mineral',
    field: 'Metallic Content',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${SM}`,
    newName: 'Cassava Cloves,Coal.Gold.Iron Ore.Lead.Lime Stone.Marble.Tin',
  },
  {
    name: 'Hibiscus',
    field: 'Flower Content',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: AG,
    newName: '',
  },
  {
    name: 'Cashew Nut,Cloves',
    field: 'Packing',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${AG}`,
    newName: 'Cashew Nut,Cassava Cloves',
  },
  {
    name: 'Cashew Nut,Birds Eye Chilli,Soya Beans,Ginger,Cloves,Hibiscus',
    field: 'Shipment',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${AG},${AG},${AG},${AG},${AG}`,
    newName:
      'Cashew Nut,Bird Eye Chili Peppers,Soy Beans,Ginger,Cassava Cloves,Hibiscus',
  },
  {
    name: 'Cashew Nut,Birds Eye Chilli,Soya Beans,Ginger,Cloves,Hibiscus',
    field: 'Port of loading',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${AG},${AG},${AG},${AG},${AG}`,
    newName:
      'Cashew Nut,Bird Eye Chili Peppers,Soy Beans,Ginger,Cassava Cloves,Hibiscus',
  },
  {
    name: 'Sesame Seeds',
    field: 'Moisture and Volatiles',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Sesame Seeds',
  },
  {
    name: 'Cocoa,Hibiscus',
    field: 'Mold',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG},${AG}`,
    newName: 'Cocoa',
  },
  {
    name: 'Hibiscus',
    field: 'Full flower',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Hibiscus',
  },
  {
    name: 'Hibiscus',
    field: 'Breakages',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Hibiscus',
  },
  {
    name: 'Cocoa',
    field: 'Insect',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Cocoa',
  },
  {
    name: 'Cocoa',
    field: 'Slate',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Cocoa',
  },
  {
    name: 'Cocoa',
    field: 'Flat',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Cocoa',
  },
  {
    name: 'Cocoa',
    field: 'Clusters',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Cocoa',
  },
  {
    name: 'Cashew Nut',
    field: 'Kernel Output Ratio',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Cashew Nut',
  },
  {
    name: 'Soya Beans',
    field: 'Cleaned/Uncleaned',
    valueType: 'string',
    fieldType: 'select',
    fieldOptions: [
      {
        label: 'Cleaned',
        key: 'cleaned',
        value: 'Cleaned',
      },
      {
        label: 'Uncleaned',
        key: 'uncleaned',
        value: 'Uncleaned',
      },
    ],
    category: `${AG}`,
    newName: 'Soy Beans',
  },
  {
    name: 'Sesame Seeds',
    field: 'Purity',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Sesame Seeds',
  },
  {
    name: 'Sesame Seeds',
    field: 'Peroxide No of extracted seasame oil',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Sesame Seeds',
  },
  {
    name: 'Sesame Seeds',
    field: 'Total Ash',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Sesame Seeds',
  },
  {
    name: 'Sesame Seeds',
    field: 'Protein Content',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Sesame Seeds',
  },
  {
    name: 'Sesame Seeds',
    field: 'Free fatty acids in extracted oil as oleic acid',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Sesame Seeds',
  },
  {
    name: 'Sesame Seeds',
    field: 'Damaged and lean goods',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${AG}`,
    newName: 'Sesame Seeds',
  },
  {
    name: 'Lithium,Monazite,Tantalum,Tin,Lead,Zinc,Beryllium',
    field: 'Grade(%)',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${SM},${SM},${SM},${SM},${SM},${SM},${SM}`,
    newName: 'Lithium,Monazite,Tantalum,Tin,Lead,Zinc,Beryllium',
  },
  {
    name: 'Lithium,Monazite,Tantalum,Tin,Lead,Zinc,Beryllium,Sugar,Sugar beans',
    field: 'Additional Details',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${SM},${SM},${SM},${SM},${SM},${SM},${SM},${AG},${AG}`,
    newName:
      'Lithium,Monazite,Tantalum,Tin,Lead,Zinc,Beryllium,Sugar,Sugar beans',
  },
  {
    name: 'Tin',
    field: 'RA',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${SM}`,
    newName: 'Tin',
  },
  {
    name: 'Tantalum',
    field: 'Nb(%)',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${SM}`,
    newName: 'Tantalum',
  },
  {
    name: 'Lithium',
    field: 'L12O',
    valueType: 'string',
    fieldType: 'input',
    fieldOptions: [],
    category: `${SM}`,
    newName: 'Lithium',
  },
];

export const productTypesImages = {
  cocoa:
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1714724833/QUAD%203-TRACE/Cocoa_anz7br.jpg',
  sugar:
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1716538592/QUAD%203-TRACE/Sugar_1_dsimez.jpg',
  sugar_beans:
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1716538590/QUAD%203-TRACE/Sugar_beans_kouhkg.jpg',
  cassava_cloves:
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1714725995/QUAD%203-TRACE/Cassava_cloves_ov71lr.jpg',
  cashew_nut:
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1714724942/QUAD%203-TRACE/Cashew_kfe8xq.jpg',
  ginger:
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1714724834/QUAD%203-TRACE/Ginger_a45meg.jpg',
  hibiscus:
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1714724833/QUAD%203-TRACE/Hibiscus_evslov.jpg',
  sesame_seeds:
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1714724834/QUAD%203-TRACE/sesame_mt88g0.jpg',
  soy_beans:
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1714724832/QUAD%203-TRACE/Soy_beans_leomva.jpg',
  lithium:
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1715004231/QUAD%203-TRACE/Lithium_Spodumene_wksu4e.jpg',
  tantalum:
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1715004138/QUAD%203-TRACE/Tantalite_lraxny.jpg',
  tin: 'https://res.cloudinary.com/rensourceenergy/image/upload/v1715004138/QUAD%203-TRACE/Tin_gkkwfg.jpg',
  beryllium:
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1715004139/QUAD%203-TRACE/Berrylium_fv9srs.jpg',
  '1_beryllium':
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1715004139/QUAD%203-TRACE/Berrylium_fv9srs.jpg',
  monazite:
    'https://res.cloudinary.com/rensourceenergy/image/upload/v1715004139/QUAD%203-TRACE/Monazite_likndh.jpg',
  lead: 'https://res.cloudinary.com/rensourceenergy/image/upload/v1715004138/QUAD%203-TRACE/Lead_lyog58.jpg',
};
